version: 2.1

jobs:
  check-syntax:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run ESlint
          command: npx eslint --ext .ts,tsx src
  analyze-tsc:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run tsc
          command: npx tsc --noEmit
  accept-test:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run test
          command: npm test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy master to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - check-syntax
      - analyze-tsc
      - accept-test:
          requires:
            - check-syntax
            - analyze-tsc
      - deploy:
          requires:
            - accept-test
          filters:
            branches:
              only: master